//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EVENTS_MGR_TESTING_Entities : DbContext
    {
        public EVENTS_MGR_TESTING_Entities()
            : base("name=EVENTS_MGR_TESTING_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<LTRank> LTRanks { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
    
        public virtual ObjectResult<EVENTS_LAST_10_DAYS_Result> EVENTS_LAST_10_DAYS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EVENTS_LAST_10_DAYS_Result>("EVENTS_LAST_10_DAYS");
        }
    
        public virtual ObjectResult<EVENTS_LAST_6_MONTHS_Result> EVENTS_LAST_6_MONTHS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EVENTS_LAST_6_MONTHS_Result>("EVENTS_LAST_6_MONTHS");
        }
    
        public virtual ObjectResult<Event> EVENTS_LAST_10_DAYS1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Event>("EVENTS_LAST_10_DAYS1");
        }
    
        public virtual ObjectResult<Event> EVENTS_LAST_10_DAYS1(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Event>("EVENTS_LAST_10_DAYS1", mergeOption);
        }
    
        public virtual ObjectResult<Event> EVENTS_LAST_6_MONTHS1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Event>("EVENTS_LAST_6_MONTHS1");
        }
    
        public virtual ObjectResult<Event> EVENTS_LAST_6_MONTHS1(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Event>("EVENTS_LAST_6_MONTHS1", mergeOption);
        }
    
        public virtual ObjectResult<USER_OWNED_EVENTS_Result> USER_OWNED_EVENTS(Nullable<int> user)
        {
            var userParameter = user.HasValue ?
                new ObjectParameter("User", user) :
                new ObjectParameter("User", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USER_OWNED_EVENTS_Result>("USER_OWNED_EVENTS", userParameter);
        }
    
        public virtual ObjectResult<Event> USER_OWNED_EVENTS1(Nullable<int> user)
        {
            var userParameter = user.HasValue ?
                new ObjectParameter("User", user) :
                new ObjectParameter("User", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Event>("USER_OWNED_EVENTS1", userParameter);
        }
    
        public virtual ObjectResult<Event> USER_OWNED_EVENTS1(Nullable<int> user, MergeOption mergeOption)
        {
            var userParameter = user.HasValue ?
                new ObjectParameter("User", user) :
                new ObjectParameter("User", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Event>("USER_OWNED_EVENTS1", mergeOption, userParameter);
        }
    
        public virtual ObjectResult<AVAILABLE_EVENTS_BY_USERID_Result> AVAILABLE_EVENTS_BY_USERID(Nullable<int> user)
        {
            var userParameter = user.HasValue ?
                new ObjectParameter("User", user) :
                new ObjectParameter("User", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AVAILABLE_EVENTS_BY_USERID_Result>("AVAILABLE_EVENTS_BY_USERID", userParameter);
        }
    
        public virtual ObjectResult<CURRENT_REGISTRATIONS_BY_USERID_Result> CURRENT_REGISTRATIONS_BY_USERID(Nullable<int> user)
        {
            var userParameter = user.HasValue ?
                new ObjectParameter("User", user) :
                new ObjectParameter("User", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CURRENT_REGISTRATIONS_BY_USERID_Result>("CURRENT_REGISTRATIONS_BY_USERID", userParameter);
        }
    
        public virtual ObjectResult<ALL_EVENTS_VIEW_Result> ALL_EVENTS_VIEW()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ALL_EVENTS_VIEW_Result>("ALL_EVENTS_VIEW");
        }
    
        public virtual ObjectResult<MY_EVENTS_VIEW_Result> MY_EVENTS_VIEW(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MY_EVENTS_VIEW_Result>("MY_EVENTS_VIEW", userIdParameter);
        }
    
        public virtual ObjectResult<REGISTRATIONDETAILS_Result> REGISTRATIONDETAILS(Nullable<int> eventID)
        {
            var eventIDParameter = eventID.HasValue ?
                new ObjectParameter("EventID", eventID) :
                new ObjectParameter("EventID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<REGISTRATIONDETAILS_Result>("REGISTRATIONDETAILS", eventIDParameter);
        }
    
        public virtual ObjectResult<CONFIRMED_HOUR_TOTALS_BY_USER_Result> CONFIRMED_HOUR_TOTALS_BY_USER(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CONFIRMED_HOUR_TOTALS_BY_USER_Result>("CONFIRMED_HOUR_TOTALS_BY_USER", userIDParameter);
        }
    }
}
