//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManager
{
    using System;
    
    public enum RegistrationStats : int
    {
        Pending = 1,
        Confirmed = 2,
        Standby = 3,
        Declined = 4,
        Deleted = 5,
        NoShow = 6
    }
}
