//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManager
{
    using System;
    
    public enum RegistrationStatus : int
    {
        Confirmed = 5,
        Standby = 6,
        Pending = 7,
        Declined = 8,
        Deleted = 11,
        NoShow = 12,
        ConfirmPending = 1,
        StandbyPending = 2,
        Transferred = 9,
        TransferPending = 3,
        Withdrawn = 10,
        WithdrawlPending = 4
    }
}
